// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/project.proto

package projectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_proto_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProjectRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateProjectRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_proto_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateProjectResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetUserProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectsRequest) Reset() {
	*x = GetUserProjectsRequest{}
	mi := &file_proto_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectsRequest) ProtoMessage() {}

func (x *GetUserProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectsRequest.ProtoReflect.Descriptor instead.
func (*GetUserProjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProjectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "client" or "freelancer"
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProject) Reset() {
	*x = UserProject{}
	mi := &file_proto_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProject) ProtoMessage() {}

func (x *UserProject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProject.ProtoReflect.Descriptor instead.
func (*UserProject) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{3}
}

func (x *UserProject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UserProject) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *UserProject) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserProject) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UserProject) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetUserProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*UserProject         `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectsResponse) Reset() {
	*x = GetUserProjectsResponse{}
	mi := &file_proto_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectsResponse) ProtoMessage() {}

func (x *GetUserProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectsResponse.ProtoReflect.Descriptor instead.
func (*GetUserProjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProjectsResponse) GetProjects() []*UserProject {
	if x != nil {
		return x.Projects
	}
	return nil
}

type GetProjectDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectDetailsRequest) Reset() {
	*x = GetProjectDetailsRequest{}
	mi := &file_proto_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectDetailsRequest) ProtoMessage() {}

func (x *GetProjectDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetProjectDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{5}
}

func (x *GetProjectDetailsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type Freelancer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Freelancer) Reset() {
	*x = Freelancer{}
	mi := &file_proto_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Freelancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Freelancer) ProtoMessage() {}

func (x *Freelancer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Freelancer.ProtoReflect.Descriptor instead.
func (*Freelancer) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{6}
}

func (x *Freelancer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Freelancer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProjectDetailsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProjectId           string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName         string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ClientId            string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AssignedFreelancers []*Freelancer          `protobuf:"bytes,5,rep,name=assigned_freelancers,json=assignedFreelancers,proto3" json:"assigned_freelancers,omitempty"`
	StartDate           string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate             string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetProjectDetailsResponse) Reset() {
	*x = GetProjectDetailsResponse{}
	mi := &file_proto_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectDetailsResponse) ProtoMessage() {}

func (x *GetProjectDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetProjectDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{7}
}

func (x *GetProjectDetailsResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetProjectDetailsResponse) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *GetProjectDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProjectDetailsResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetProjectDetailsResponse) GetAssignedFreelancers() []*Freelancer {
	if x != nil {
		return x.AssignedFreelancers
	}
	return nil
}

func (x *GetProjectDetailsResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetProjectDetailsResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type DiscoverProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []string               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	ExperienceMin int32                  `protobuf:"varint,2,opt,name=experience_min,json=experienceMin,proto3" json:"experience_min,omitempty"`
	Languages     []string               `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverProjectsRequest) Reset() {
	*x = DiscoverProjectsRequest{}
	mi := &file_proto_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverProjectsRequest) ProtoMessage() {}

func (x *DiscoverProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverProjectsRequest.ProtoReflect.Descriptor instead.
func (*DiscoverProjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoverProjectsRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *DiscoverProjectsRequest) GetExperienceMin() int32 {
	if x != nil {
		return x.ExperienceMin
	}
	return 0
}

func (x *DiscoverProjectsRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

type DiscoveredProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredProject) Reset() {
	*x = DiscoveredProject{}
	mi := &file_proto_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredProject) ProtoMessage() {}

func (x *DiscoveredProject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredProject.ProtoReflect.Descriptor instead.
func (*DiscoveredProject) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoveredProject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DiscoveredProject) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *DiscoveredProject) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DiscoveredProject) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DiscoveredProject) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *DiscoveredProject) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type DiscoverProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*DiscoveredProject   `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverProjectsResponse) Reset() {
	*x = DiscoverProjectsResponse{}
	mi := &file_proto_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverProjectsResponse) ProtoMessage() {}

func (x *DiscoverProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverProjectsResponse.ProtoReflect.Descriptor instead.
func (*DiscoverProjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoverProjectsResponse) GetProjects() []*DiscoveredProject {
	if x != nil {
		return x.Projects
	}
	return nil
}

type AssignFreelancerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,2,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignFreelancerRequest) Reset() {
	*x = AssignFreelancerRequest{}
	mi := &file_proto_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignFreelancerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignFreelancerRequest) ProtoMessage() {}

func (x *AssignFreelancerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignFreelancerRequest.ProtoReflect.Descriptor instead.
func (*AssignFreelancerRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{11}
}

func (x *AssignFreelancerRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AssignFreelancerRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

type AssignFreelancerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,2,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignFreelancerResponse) Reset() {
	*x = AssignFreelancerResponse{}
	mi := &file_proto_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignFreelancerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignFreelancerResponse) ProtoMessage() {}

func (x *AssignFreelancerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignFreelancerResponse.ProtoReflect.Descriptor instead.
func (*AssignFreelancerResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{12}
}

func (x *AssignFreelancerResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AssignFreelancerResponse) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *AssignFreelancerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_proto_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type UpdateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectResponse) Reset() {
	*x = UpdateProjectResponse{}
	mi := &file_proto_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectResponse) ProtoMessage() {}

func (x *UpdateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateProjectResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_proto_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_proto_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteProjectResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteProjectResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_project_proto protoreflect.FileDescriptor

const file_proto_project_proto_rawDesc = "" +
	"\n" +
	"\x13proto/project.proto\x12\aproject\"\xb2\x01\n" +
	"\x14CreateProjectRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"N\n" +
	"\x15CreateProjectResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"1\n" +
	"\x16GetUserProjectsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9d\x01\n" +
	"\vUserProject\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\"K\n" +
	"\x17GetUserProjectsResponse\x120\n" +
	"\bprojects\x18\x01 \x03(\v2\x14.project.UserProjectR\bprojects\"9\n" +
	"\x18GetProjectDetailsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"9\n" +
	"\n" +
	"Freelancer\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x9e\x02\n" +
	"\x19GetProjectDetailsResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12F\n" +
	"\x14assigned_freelancers\x18\x05 \x03(\v2\x13.project.FreelancerR\x13assignedFreelancers\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\"v\n" +
	"\x17DiscoverProjectsRequest\x12\x16\n" +
	"\x06skills\x18\x01 \x03(\tR\x06skills\x12%\n" +
	"\x0eexperience_min\x18\x02 \x01(\x05R\rexperienceMin\x12\x1c\n" +
	"\tlanguages\x18\x03 \x03(\tR\tlanguages\"\xce\x01\n" +
	"\x11DiscoveredProject\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\"R\n" +
	"\x18DiscoverProjectsResponse\x126\n" +
	"\bprojects\x18\x01 \x03(\v2\x1a.project.DiscoveredProjectR\bprojects\"]\n" +
	"\x17AssignFreelancerRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12#\n" +
	"\rfreelancer_id\x18\x02 \x01(\tR\ffreelancerId\"v\n" +
	"\x18AssignFreelancerResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12#\n" +
	"\rfreelancer_id\x18\x02 \x01(\tR\ffreelancerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x95\x01\n" +
	"\x14UpdateProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"N\n" +
	"\x15UpdateProjectResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x14DeleteProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"N\n" +
	"\x15DeleteProjectResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xe4\x04\n" +
	"\x0eProjectService\x12N\n" +
	"\rCreateProject\x12\x1d.project.CreateProjectRequest\x1a\x1e.project.CreateProjectResponse\x12T\n" +
	"\x0fGetUserProjects\x12\x1f.project.GetUserProjectsRequest\x1a .project.GetUserProjectsResponse\x12Z\n" +
	"\x11GetProjectDetails\x12!.project.GetProjectDetailsRequest\x1a\".project.GetProjectDetailsResponse\x12W\n" +
	"\x10DiscoverProjects\x12 .project.DiscoverProjectsRequest\x1a!.project.DiscoverProjectsResponse\x12W\n" +
	"\x10AssignFreelancer\x12 .project.AssignFreelancerRequest\x1a!.project.AssignFreelancerResponse\x12N\n" +
	"\rUpdateProject\x12\x1d.project.UpdateProjectRequest\x1a\x1e.project.UpdateProjectResponse\x12N\n" +
	"\rDeleteProject\x12\x1d.project.DeleteProjectRequest\x1a\x1e.project.DeleteProjectResponseB\"Z internal/project/proto;projectpbb\x06proto3"

var (
	file_proto_project_proto_rawDescOnce sync.Once
	file_proto_project_proto_rawDescData []byte
)

func file_proto_project_proto_rawDescGZIP() []byte {
	file_proto_project_proto_rawDescOnce.Do(func() {
		file_proto_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_project_proto_rawDesc), len(file_proto_project_proto_rawDesc)))
	})
	return file_proto_project_proto_rawDescData
}

var file_proto_project_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_project_proto_goTypes = []any{
	(*CreateProjectRequest)(nil),      // 0: project.CreateProjectRequest
	(*CreateProjectResponse)(nil),     // 1: project.CreateProjectResponse
	(*GetUserProjectsRequest)(nil),    // 2: project.GetUserProjectsRequest
	(*UserProject)(nil),               // 3: project.UserProject
	(*GetUserProjectsResponse)(nil),   // 4: project.GetUserProjectsResponse
	(*GetProjectDetailsRequest)(nil),  // 5: project.GetProjectDetailsRequest
	(*Freelancer)(nil),                // 6: project.Freelancer
	(*GetProjectDetailsResponse)(nil), // 7: project.GetProjectDetailsResponse
	(*DiscoverProjectsRequest)(nil),   // 8: project.DiscoverProjectsRequest
	(*DiscoveredProject)(nil),         // 9: project.DiscoveredProject
	(*DiscoverProjectsResponse)(nil),  // 10: project.DiscoverProjectsResponse
	(*AssignFreelancerRequest)(nil),   // 11: project.AssignFreelancerRequest
	(*AssignFreelancerResponse)(nil),  // 12: project.AssignFreelancerResponse
	(*UpdateProjectRequest)(nil),      // 13: project.UpdateProjectRequest
	(*UpdateProjectResponse)(nil),     // 14: project.UpdateProjectResponse
	(*DeleteProjectRequest)(nil),      // 15: project.DeleteProjectRequest
	(*DeleteProjectResponse)(nil),     // 16: project.DeleteProjectResponse
}
var file_proto_project_proto_depIdxs = []int32{
	3,  // 0: project.GetUserProjectsResponse.projects:type_name -> project.UserProject
	6,  // 1: project.GetProjectDetailsResponse.assigned_freelancers:type_name -> project.Freelancer
	9,  // 2: project.DiscoverProjectsResponse.projects:type_name -> project.DiscoveredProject
	0,  // 3: project.ProjectService.CreateProject:input_type -> project.CreateProjectRequest
	2,  // 4: project.ProjectService.GetUserProjects:input_type -> project.GetUserProjectsRequest
	5,  // 5: project.ProjectService.GetProjectDetails:input_type -> project.GetProjectDetailsRequest
	8,  // 6: project.ProjectService.DiscoverProjects:input_type -> project.DiscoverProjectsRequest
	11, // 7: project.ProjectService.AssignFreelancer:input_type -> project.AssignFreelancerRequest
	13, // 8: project.ProjectService.UpdateProject:input_type -> project.UpdateProjectRequest
	15, // 9: project.ProjectService.DeleteProject:input_type -> project.DeleteProjectRequest
	1,  // 10: project.ProjectService.CreateProject:output_type -> project.CreateProjectResponse
	4,  // 11: project.ProjectService.GetUserProjects:output_type -> project.GetUserProjectsResponse
	7,  // 12: project.ProjectService.GetProjectDetails:output_type -> project.GetProjectDetailsResponse
	10, // 13: project.ProjectService.DiscoverProjects:output_type -> project.DiscoverProjectsResponse
	12, // 14: project.ProjectService.AssignFreelancer:output_type -> project.AssignFreelancerResponse
	14, // 15: project.ProjectService.UpdateProject:output_type -> project.UpdateProjectResponse
	16, // 16: project.ProjectService.DeleteProject:output_type -> project.DeleteProjectResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_project_proto_init() }
func file_proto_project_proto_init() {
	if File_proto_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_project_proto_rawDesc), len(file_proto_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_project_proto_goTypes,
		DependencyIndexes: file_proto_project_proto_depIdxs,
		MessageInfos:      file_proto_project_proto_msgTypes,
	}.Build()
	File_proto_project_proto = out.File
	file_proto_project_proto_goTypes = nil
	file_proto_project_proto_depIdxs = nil
}
